apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: registry.gitlab.com/antoan-a-ignatov/k8s-identity-observability-platform:keycloak-eea740c3
          args: ["start", "--optimized"]
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 9000
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef: { name: keycloak-admin, key: username }
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef: { name: keycloak-admin, key: password }
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef: { name: keycloak-db, key: db-url }
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef: { name: keycloak-db, key: db-username }
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef: { name: keycloak-db, key: db-password }
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
          resources:
            requests: { memory: "512Mi", cpu: "250m" }
            limits: { memory: "1Gi", cpu: "1" }
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: identity
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
