apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: identity
type: Opaque
stringData:
  username: admin
  password: QyxHUDYqvmiweNl2wwCK/llS
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  namespace: identity
type: Opaque
stringData:
  db-url: "jdbc:postgresql://postgres.data.svc.cluster.local:5432/keycloak"
  db-username: keycloak
  db-password: cB1A6B1WXHAtJLDLbghgjSJ9NwcZtR9A
