apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/antoan-a-ignatov/k8s-identity-observability-platform.git
    targetRevision: main
    path: manifests/app
    directory:
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
